cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift
    - ~/.swiftenv

language: generic

matrix:
  include:
    - os: osx
      name: Swift 5.1
      osx_image: xcode11
      install:
        - node -v
        - npm install -g danger
      script:
        - swift run danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1
      script:
        - DEBUG='*' swift run danger-swift ci
